"""teacher code column

Revision ID: 23f6e0df3451
Revises: d5aac0fabd4a
Create Date: 2018-03-16 08:30:38.549930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f6e0df3451'
down_revision = 'd5aac0fabd4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teacher_code', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['teacher_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'teacher_code')
    # ### end Alembic commands ###
